BedrockStreaming/forms

documentation/nx.md

docs(nx): add some doc about nx philosophy

---

package.json
yarn.lock

build(release): bump semver for notes fix

---

apps/docsite/docusaurus.config.js
package.json
yarn.lock

fix(apps/docsite): fix base url

---

apps/docsite/src/css/custom.css
apps/docsite/src/theme/Root.js

feat(apps/docsite): use bedrock colors

---

libs/form-builder/src/lib/constants.ts
libs/form-builder/src/lib/formBuilder.tsx

feat(libs/form-builder): export inner components classnames

---

libs/form-builder/src/lib/formBuilder.tsx

fix(libs/form-builder): use the right field rules

---

apps/docsite/docusaurus.config.js
package.json
yarn.lock

fix(apps/docsite): code blocks colorization

---

apps/demo/src/app/config.ts
apps/demo/src/app/examples/with-material-ui/dictionary.ts
apps/demo/src/app/examples/with-material-ui/dictionary/checkBox.component.tsx
apps/demo/src/app/examples/with-material-ui/form.component.tsx
apps/demo/src/app/examples/with-styled-components/dictionary.ts
apps/demo/src/app/examples/with-styled-components/dictionary/checkBox.component.tsx
apps/demo/src/app/examples/with-styled-components/dictionary/select.component.tsx
apps/demo/src/app/examples/with-styled-components/dictionary/styled.js
apps/demo/src/app/extraValidation.ts
apps/docsite/docs/form-builder.md
apps/docsite/docs/overview.md
documentation/release.md
libs/form-builder/README.md
libs/form-builder/src/lib/formBuilder.tsx
libs/form-builder/src/lib/types.ts
libs/form-builder/src/lib/utils/conditionalFields.utils.ts
libs/form-builder/src/lib/utils/getSchemaInfo.util.ts
package.json
yarn.lock

feat(libs/form-builder): add conditional fields

---

apps/demo/src/app/extraValidation.ts
apps/demo/src/app/hooks/useLoginSubmit.hook.ts
apps/demo/src/app/login.config.ts
apps/demo/src/app/register.config.ts
apps/docsite/src/form/config.js
libs/form-builder/src/lib/__tests__/formBuilder.spec.tsx
libs/form-builder/src/lib/types.ts
libs/form-context/src/lib/__tests__/forms.actions.spec.ts
libs/form-editor/src/lib/forms/dictionary/config.ts
libs/form-editor/src/lib/forms/extraValidation/config.ts
libs/form-editor/src/lib/forms/field/config.ts
libs/form-editor/src/lib/forms/field/field.form.tsx
libs/form-editor/src/lib/forms/schema/updateConfig.ts
libs/form-editor/src/lib/forms/schema/upload/config.ts
libs/form-editor/src/lib/forms/step/config.ts
libs/form-editor/src/lib/generator.reducer.ts
libs/form-redux/src/lib/__tests__/forms.actions.spec.ts

refactor(libs/form-builder): remove title from field type

---

libs/form-builder/src/lib/formBuilder.tsx

feat(libs/form-builder): add form props

---

package.json
yarn.lock

build(deps): resolve node fetch

---

.github/workflows/labelling.yml

ci(repository): fix action version

---

libs/form-builder/package.json
libs/form-builder/src/lib/__tests__/fixtures.tsx
libs/form-builder/src/lib/components/stepper.component.tsx
libs/form-builder/src/lib/formBuilder.tsx
libs/form-builder/src/lib/hooks/useAutoFocus.hook.ts
libs/form-builder/src/lib/types.ts
libs/form-builder/src/lib/utils/error.util.ts
libs/form-builder/src/lib/utils/getSchemaInfo.util.ts
libs/form-builder/src/lib/utils/handleFormBuilderError.util.ts
libs/form-builder/src/lib/utils/object.utils.ts
libs/form-builder/src/lib/utils/validation.utils.ts
libs/form-context/package.json
libs/form-context/src/lib/__tests__/forms.selectors.spec.ts
libs/form-context/src/lib/form-context.tsx
libs/form-context/src/lib/forms.reducer.ts
libs/form-context/src/lib/forms.selectors.ts
libs/form-editor/package.json
libs/form-redux/package.json
libs/form-redux/src/lib/__tests__/forms.reducer.spec.ts
libs/form-redux/src/lib/__tests__/forms.selectors.spec.ts
libs/form-redux/src/lib/forms.reducer.ts
libs/form-redux/src/lib/forms.selectors.ts
libs/form-validation-rule-list/package.json
libs/form-validation-rule-list/src/lib/components/validationRuleList.component.tsx
libs/form-validation-rule-list/src/lib/getValidationRulesHints.ts
libs/form-validation-rule-list/src/lib/rule.ts

refactor(libs/form-builder): remove lodash usage

---

libs/form-builder/package.json
libs/form-builder/src/lib/formBuilder.tsx
libs/form-builder/src/lib/hooks/__tests__/useDevtools.hook.spec.ts
libs/form-builder/src/lib/hooks/useDebug.hook.tsx
libs/form-builder/src/lib/hooks/useDevtools.hook.tsx
libs/form-context/package.json
libs/form-validation-rule-list/package.json

build(libs/form-builder): lazy load devtools

---

.github/CONTRIBUTING.md
README.md
apps/demo/src/app/examples/with-styled-components/login/form.component.tsx

Updating the docs
Make the dev exp starting on the project a bit smoother.

docs(project): update the documentation

---

.github/workflows/prerelease.yml
.vscode/settings.json
libs/form-builder/project.json
libs/form-context/project.json
libs/form-editor/project.json
libs/form-redux/project.json
libs/form-validation-rule-list/project.json
project.json

ci(pre-release): create a prerelease workflow

---

.github/workflows/prerelease.yml
libs/form-builder/src/lib/constants.ts

ci(pre-release): fix pipeline

---

.github/workflows/main.yml
.github/workflows/release.yml
apps/demo/jest.config.js
codecov.yml
libs/form-builder/jest.config.js
libs/form-context/jest.config.js
libs/form-editor/jest.config.js
libs/form-redux/jest.config.js
libs/form-validation-rule-list/jest.config.js

Bring back Codecov
#69 
Codecoverage is one indicator among others that should be considered

ci(codecov): fix code coverage

---

package.json
yarn.lock

build(deps): fix vulnerabilities

---

nx.json
package.json
yarn.lock

Nx cloud is free, it is supposed to accelerate CI runs with nx commands by caching a few things. Let's try it !

ci(nx-cloud): optin on nx cloud computing

---

.husky/pre-push
.validate-branch-namerc.js
package.json
yarn.lock

ci(git): prevent slash and uppercase in branch names
